channels:
  - conda-forge
dependencies:
  - python=3.9
  - eccodes=2.34.1
  - xarray=2024.2.0
  - pandas=2.2.1
  - netCDF4=1.6.5
  - scipy=1.12.0
  - pint=0.23
  - numba=0.59.0
  - boto3=1.34.55
  - pip:
    - cfgrib==0.9.10.4
